src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

     /**
     * @gedmo\Slug(fields={"name"})
     */    
    #[ORM\Column(type: 'string', length: 120)]
    private $slug;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'categories')]
    private $parent;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    private $categories;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Post::class)]
    private $posts;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->posts = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /*
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    } */

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setParent($this);
        }

        return $this;
    }

    public function removeCategory(self $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getParent() === $this) {
                $category->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setCategory($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getCategory() === $this) {
                $post->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    /**
     * @Gedmo\Timestampable(on="create")
     */
    #[ORM\Column(type: 'datetime_immutable')]
    private $CreatedAt;

    #[ORM\Column(type: 'text')]
    private $Content;

    #[ORM\ManyToOne(targetEntity: Post::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $post;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CategoryController extends AbstractController
{
    #[Route('/category', name: 'app_category')]
    /*public function index(): Response
    {
        return $this->render('category/index.html.twig', [
            'controller_name' => 'CategoryController',
        ]);
    } */

    public function index(CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->findAll();
        //$name = $categoryRepository->findPostsByCategory();

        return $this->render('category/cat-index.html.twig', [
            'categories' => $categories,
        ]);
    }

}

templates/category/cat-index.html.twig
{% extends 'amazing.html.twig' %}

{% block title %}Catégories{% endblock %}

{% block body %}

<div class="accordion max-w-md mx-auto md:max-w-2xl" id="accordionExample">
  <div class="accordion-item bg-gradient-to-r from-blue-500 to-blue-900 border border-gray-200">
    {% for category in categories %} 
      <div class="accordion-header mx-auto text-center mb-0" id="heading{{ category.id }}">
        <button class="
            accordion-button
            collapsed
            relative
            flex
            items-center
            bg-blue-500
            rounded-md
            text-2xl
            py-4
            pl-10
            mb-10
            w-full
            shadow-3xl
            hover:bg-blue-800 hover:text-white
            transition
            focus:outline-none" 
            type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ category.id }}" aria-expanded="false" aria-controls="collapse{{ category.id }}">
            {{ category.name }}
        </button>
      </div>
      <div id="collapse{{ category.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ category.id }}" data-bs-parent="#accordionExample">
        <div class="accordion-body py-4 px-5">
          {% for post in category.posts %}
            <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-10 mt-8">
              <div class="md:flex">
                <div class="md:shrink-0">
                    <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.image }}" alt="">
                </div>
                <div class="p-8">
                  <a href="{{ path('post_view', {slug: post.slug}) }}">
                      <div class="uppercase tracking-wide text-xl text-blue-800 font-semibold">
                      {{ post.title }}
                      </div>
                      <p class="mt-2 text-slate-700">
                      {{ post.content | u.truncate(150, '...') | raw }}  {# | raw , |date, etc sont des filtres twig #}
                      </p>
                  </a>
                
                  <div class="text-slate-500">
                      Rédigé par
                      {{ post.user.email }} {# on peut ici faire réf à user ET email grâce aux relations entre entités #}
                      le {{ post.createdAt | date('d/m/Y') }}
                      à {{ post.createdAt | date('H:i') }}
                      - classé dans {{ post.category.name }}
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}  
        </div>
      </div>
    {% endfor %}
  </div>
</div>

  {#
  <div class="accordion-item bg-white border border-gray-200">
    <h2 class="accordion-header mb-0" id="headingTwo">
      <button class="
        accordion-button
        collapsed
        relative
        flex
        items-center
        w-full
        py-4
        px-5
        text-base text-gray-800 text-left
        bg-white
        border-0
        rounded-none
        transition
        focus:outline-none
      " type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false"
        aria-controls="collapseTwo">
        Accordion Item #2
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
      data-bs-parent="#accordionExample">
      <div class="accordion-body py-4 px-5">
        <strong>This is the second item's accordion body.</strong> It is hidden by default,
        until the collapse plugin adds the appropriate classes that we use to style each
        element. These classes control the overall appearance, as well as the showing and
        hiding via CSS transitions. You can modify any of this with custom CSS or overriding
        our default variables. It's also worth noting that just about any HTML can go within
        the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item bg-white border border-gray-200">
    <h2 class="accordion-header mb-0" id="headingThree">
      <button class="
        accordion-button
        collapsed
        relative
        flex
        items-center
        w-full
        py-4
        px-5
        text-base text-gray-800 text-left
        bg-white
        border-0
        rounded-none
        transition
        focus:outline-none
      " type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false"
        aria-controls="collapseThree">
        Accordion Item #3
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
      data-bs-parent="#accordionExample">
      <div class="accordion-body py-4 px-5">
        <strong>This is the third item's accordion body.</strong> It is hidden by default,
        until the collapse plugin adds the appropriate classes that we use to style each
        element. These classes control the overall appearance, as well as the showing and
        hiding via CSS transitions. You can modify any of this with custom CSS or overriding
        our default variables. It's also worth noting that just about any HTML can go within
        the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
#}

{#
    <div class="text-white text-center text-3xl bg-gradient-to-r from-blue-500 to-blue-900 rounded-md font-semibold py-2 max-w-md mx-auto md:max-w-2xl mb-10 sticky top-[130px]">
        <h1>Liste des catégories</h1>
    </div>

    {% for category in categories %}
    <details>
        <summary class="bg-white rounded-md mx-auto w-2/3 md:max-w-2xl mb-10 py-4 pl-4 shadow-2xl hover:bg-blue-800 hover:text-white">
                {{ category.name }}
        </summary>
        
        <ul>
            {% for post in category.posts %}
            <li>
                <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-10 mt-8">
                    <div class="md:flex">
                        <div class="md:shrink-0">
                            <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.image }}" alt="">
                        </div>
                        <div class="p-8">
                            <a href="{{ path('post_view', {slug: post.slug}) }}">
                                <div class="uppercase tracking-wide text-xl text-blue-800 font-semibold">
                                {{ post.title }}
                                </div>
                                <p class="mt-2 text-slate-700">
                                {{ post.content | u.truncate(150, '...') | raw }}
                                </p>
                            </a>
                        <div class="text-slate-500">
                            Rédigé par
                            {{ post.user.email }}
                            le {{ post.createdAt | date('d/m/Y') }}
                            à {{ post.createdAt | date('H:i') }}
                            - classé dans {{ post.category.name }}
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </details>               
    {% endfor %}
    #}
{% endblock %}

templates/category/index.html.twig
{% extends 'amazing.html.twig' %}

{% block title %}Catégories{% endblock %}

{% block body %}

    <div class="text-white text-center text-3xl bg-gradient-to-r from-blue-500 to-blue-900 rounded-md font-semibold py-2 max-w-md mx-auto md:max-w-2xl mb-10 sticky top-[130px]">
        <h1>Liste des catégories</h1>
    </div>

    {% for category in categories %}
    <details>
        <summary class="bg-white rounded-md mx-auto w-2/3 md:max-w-2xl mb-10 py-4 pl-4 shadow-2xl hover:bg-blue-800 hover:text-white">
                {{ category.name }}
        </summary>
        
        <ul>
            {% for post in category.posts %}
            <li>
                <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-10 mt-8">
                    <div class="md:flex">
                        <div class="md:shrink-0">
                            <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.image }}" alt="">
                        </div>
                        <div class="p-8">
                            <a href="{{ path('post_view', {slug: post.slug}) }}">
                                <div class="uppercase tracking-wide text-xl text-blue-800 font-semibold">
                                {{ post.title }}
                                </div>
                                <p class="mt-2 text-slate-700">
                                {{ post.content | u.truncate(150, '...') | raw }}  {# | raw , |date, etc sont des filtres twig #}
                                </p>
                            </a>
                        <div class="text-slate-500">
                            Rédigé par
                            {{ post.user.email }} {# on peut ici faire réf à user ET email grâce aux relations entre entités #}
                            le {{ post.createdAt | date('d/m/Y') }}
                            à {{ post.createdAt | date('H:i') }}
                            - classé dans {{ post.category.name }}
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </details>                 
    {% endfor %}
{% endblock %}

templates/category/old-cat-index.twig
{% extends 'amazing.html.twig' %}

{% block title %}Catégories{% endblock %}

{% block body %}

    <div class="text-white text-center text-3xl bg-gradient-to-r from-blue-500 to-blue-900 rounded-md font-semibold py-2 max-w-md mx-auto md:max-w-2xl mb-10 sticky top-[130px]">
        <h1>Liste des catégories</h1>
    </div>

    {% for category in categories %}
    <details>
        <summary class="bg-white rounded-md mx-auto w-2/3 md:max-w-2xl mb-10 py-4 pl-4 shadow-2xl hover:bg-blue-800 hover:text-white">
                {{ category.name }}
        </summary>
        
        <ul>
            {% for post in category.posts %}
            <li>
                <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-10 mt-8">
                    <div class="md:flex">
                        <div class="md:shrink-0">
                            <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.image }}" alt="">
                        </div>
                        <div class="p-8">
                            <a href="{{ path('post_view', {slug: post.slug}) }}">
                                <div class="uppercase tracking-wide text-xl text-blue-800 font-semibold">
                                {{ post.title }}
                                </div>
                                <p class="mt-2 text-slate-700">
                                {{ post.content | u.truncate(150, '...') | raw }}  {# | raw , |date, etc sont des filtres twig #}
                                </p>
                            </a>
                        <div class="text-slate-500">
                            Rédigé par
                            {{ post.user.email }} {# on peut ici faire réf à user ET email grâce aux relations entre entités #}
                            le {{ post.createdAt | date('d/m/Y') }}
                            à {{ post.createdAt | date('H:i') }}
                            - classé dans {{ post.category.name }}
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </details>                 
    {% endfor %}

{# Sauvegarde code de cat-index-html.twig #}
<div class="accordion max-w-md mx-auto md:max-w-2xl" id="accordionExample">
  <div class="accordion-item bg-gradient-to-r from-blue-500 to-blue-900 border border-gray-200"> 
    {% for category in categories %}  
        <div class="accordion-header mx-auto text-center mb-0" id="heading{{ category.id }}">
          <button class="
              accordion-button
              collapsed
              relative
              flex
              items-center
              bg-blue-500
              rounded-md
              text-2xl
              py-4
              pl-10
              mb-10
              w-full
              shadow-3xl
              hover:bg-blue-800 hover:text-white" 
              type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ category.id }}" aria-controls="collapse{{ category.id }}">
              {{ category.name }}
          </button>
        </div>
        <div id="collapse{{ category.id }}" class="accordion-collapse collapse " aria-labelledby="heading{{ category.id }}"
        data-bs-parent="#accordionExample">
            {% for post in category.posts %}
                <ul>
                    <div class="accordion-body py-4 px-5">
                        <li>
                            <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl mb-10 mt-8">
                                <div class="md:flex">
                                    <div class="md:shrink-0">
                                        <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.image }}" alt="">
                                    </div>
                                    <div class="p-8">
                                        <a href="{{ path('post_view', {slug: post.slug}) }}">
                                            <div class="uppercase tracking-wide text-xl text-blue-800 font-semibold">
                                            {{ post.title }}
                                            </div>
                                            <p class="mt-2 text-slate-700">
                                            {{ post.content | u.truncate(150, '...') | raw }}  {# | raw , |date, etc sont des filtres twig #}
                                            </p>
                                        </a>
                                    <div class="text-slate-500">
                                        Rédigé par
                                        {{ post.user.email }} {# on peut ici faire réf à user ET email grâce aux relations entre entités #}
                                        le {{ post.createdAt | date('d/m/Y') }}
                                        à {{ post.createdAt | date('H:i') }}
                                        - classé dans {{ post.category.name }}
                                    </div>
                                </div>
                            </div>
                        </li>
                    </div>
                </ul>
            {% endfor %}
        </div>
    {% endfor %}
  </div>


{% endblock %}